### PR TITLE
Added working for bumping the version when bump=='auto' with edge cases

### PR DESCRIPTION
**Pull request by Rsvyas**

### CODE REVIEW

**Comment by otakup0pe** [comment]
ok if you merge in from master then this should fix travis

https://github.com/otakup0pe/avakas/commit/b87049d540ae31dc0ce7bf80a681e5a37bef69e1

**Comment by otakup0pe** [comment]
So I guess git branches are case insensitive on macs? Who knew! The following things should be done before we merge this

- Update README with usage information
- Add more tests for edge cases
- Remove the `.idea` folder and add it to `.gitignore`

**Comment by otakup0pe** [comment]
A bunch of the `multibump because of git commit containing words major and patch` tests seem duplicated or not complete?

**Comment by Rsvyas** [comment]
Have updated the test case commit strings for these bunch of multibumps. Though the output of 3 out of 4 of these tests are same, the commit messages are now different to verify the results.

**Comment by otakup0pe** [comment]
The tests you added do pass, but there are some cases missing (and do not currently pass).

```
@test "bump minor even if there is another commit with the word patch" {
    commit_to_repo "$REPO" "minor - new feature"
    commit_to_repo "$REPO" "patch - fix a bug"
    run avakas_wrapper bump "$REPO" auto
    [ "$status" -eq 0 ]
    scan_lines "Version updated from 0.0.1 to 0.1.0"  "${lines[@]}"
}
@test "only bump once per commit" {
    commit_to_repo "$REPO" "patch"
    run avakas_wrapper bump "$REPO" auto
    [ "$status" -eq 0 ]
    scan_lines "Version updated from 0.0.1 to 0.1.0"  "${lines[@]}"
    run avakas_wrapper bump "$REPO" auto
    [ "$status" -eq 0 ]
    run	avakas_wrapper show "$REPO"
    scan_lines "Version updated from 0.0.1 to 0.1.0"  "${lines[@]}"
}
```

**Pull request closed without merging**
